binance:
  default_symbol: BTCUSDT
  production:
    api_key: s6VdoVmiH7WLAgjMekASE6yXcwpzPlwTV9uryWGM2bOAKNU3ZWMMWr1T4cLfdY09
    secret_key: 7iIEE04m84Loi80ecixsk3z3mr47WXmFfRx3GsTi3q1XDjklSN8GMxMet1oRuRBX
  test_mode: true
  testnet:
    api_key: 76shuJKddxV9x3LYMFVr92DrtAPoMYC4RVrCHFUEzj93I5Qbyl7SfDsqPOTR94hp
    secret_key: uYpLPQXHvtbMB2PNoEwOaUknEmXxFnEXwEo2WTQzOuLYJd3qeIs8TpsKXEJIHXUg
webhook:
  enabled: true
  url: https://open.feishu.cn/open-apis/bot/v2/hook/53dd4345-933a-4f22-96fc-270b67292a59
